# Generated by Django 3.2.4 on 2021-06-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singledayrequest',
            name='shift',
        ),
        migrations.AlterField(
            model_name='singledayrequest',
            name='availability',
            field=models.CharField(max_length=10),
        ),
    ]
