# Generated by Django 3.2.4 on 2021-06-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_auto_20210610_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='durationrequest',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
