# Generated by Django 3.2.4 on 2021-06-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_alter_durationrequest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='durationrequest',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='singledayrequest',
            name='note',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
