# Generated by Django 3.2.4 on 2021-06-21 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_auto_20210615_0111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DurationRequest',
        ),
    ]
