# Generated by Django 3.2.4 on 2021-06-21 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_delete_durationrequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SingleDayRequest',
            new_name='ScheduleRequest',
        ),
    ]
