# Generated by Django 3.2.4 on 2021-06-23 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_rename_singledayrequest_schedulerequest'),
    ]

    operations = [
    ]
